services:
  flink-processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flink-processor-dev
    restart: unless-stopped
    # network_mode: host allows the container to see "localhost" as your computer.
    # This lets it reach the Postgres/InfluxDB running in your other docker-compose.
    network_mode: "host"
    environment:
      # Kafka Connectivity (DigitalOcean)
      KAFKA_BOOTSTRAP_SERVERS: 163.47.8.3:9094
      KAFKA_USERNAME: user1
      KAFKA_PASSWORD: c4eFajFH2t
      KAFKA_SECURITY_PROTOCOL: SASL_PLAINTEXT
      KAFKA_SASL_MECHANISM: SCRAM-SHA-256
      
      # Database Connectivity (Local Docker via Host Network)
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: waste_management
      POSTGRES_USER: waste_admin
      POSTGRES_PASSWORD: waste_admin_password
      
      # InfluxDB Connectivity (Local Docker via Host Network)
      INFLUX_URL: http://localhost:8086
      INFLUX_TOKEN: my-super-token
      INFLUX_ORG: waste-org
      
      # App Config
      APP_ENV: development
      LOG_LEVEL: INFO
    command: ["python", "job.py", "--mode", "kafka"]
